Anonas3675/Software-Dev-Buff-Games

ProjectSourceCode/docker-compose.yaml, ProjectSourceCode/index.js, ProjectSourceCode/src/views/pages/login.hbs, ProjectSourceCode/src/views/pages/logout.hbs, ProjectSourceCode/src/views/pages/register.hbs, ProjectSourceCode/src/views/partials/footer.hbs, ProjectSourceCode/src/views/partials/nav.hbs, ProjectSourceCode/src/views/partials/title.hbs
Made changes to footer.hbs, title.hbs, nav.hbs, login.hbs, logout.hbs, register.hbs, and index.js. We now have a website UI that's alright looking and has basic functionality.
=> Website skeleton

ProjectSourceCode/src/index.js, ProjectSourceCode/src/init_data/create.sql, ProjectSourceCode/src/init_data/insert.sql
Register now uses serial properly and connects to both User_Backend and User_Information correctly.
=> Register fix

ProjectSourceCode/src/index.js, ProjectSourceCode/src/init_data/create.sql, ProjectSourceCode/src/init_data/insert.sql, ProjectSourceCode/src/views/pages/trivia.hbs
Added a basic trivia.hbs and a /question API call to select a random question from the database and display it on the table.
=> Trivia page design

ProjectSourceCode/src/init_data/create.sql
Deleting a duplicate line in the database.
=> Duplicate fix

ProjectSourceCode/src/index.js, ProjectSourceCode/src/views/pages/scoreboard.hbs
Works with the existing database schema. Each game still needs to be linked when possible
=> Basic Leaderboard for all games

ProjectSourceCode/public/resources/css/wordle.css, ProjectSourceCode/public/resources/js/wordle.js, ProjectSourceCode/src/index.js, ProjectSourceCode/src/views/pages/wordle.hbs
Working wordle page. Still need API calls to database, but basic formatting works
=> Working wordle Page

ProjectSourceCode/public/resources/css/wordle.css, ProjectSourceCode/public/resources/js/wordle.js
Modified Wordle to work with any word length
=> Any word length

ProjectSourceCode/src/init_data/insert.sql, ProjectSourceCode/src/views/pages/geoGuess.hbs
Evan's changes to geo from his branch. Ignoring index.js
=> fixed random locations, button duplication, and scoring grading.

ProjectSourceCode/src/index.js, ProjectSourceCode/src/views/pages/crossword.hbs, ProjectSourceCode/src/views/pages/scoreboard.hbs
i added a helper hbs function so that the ordering of the leaderboard would start at 1 instead of 0.
=> fixed the leaderboard ordering

ProjectSourceCode/src/views/pages/scoreboard.hbs
I've updated the look of the leaderboard page to more closely match the home page. Some further updates may be needed.
=> Updated look of scoreboard page to match Home page

ProjectSourceCode/src/resources/css/crossword.css, ProjectSourceCode/src/resources/js/crossword.js, ProjectSourceCode/src/views/pages/crossword.hbs, ProjectSourceCode/src/views/partials/nav.hbs
I finished the crossword UI and also made styling changes to nav.hbs.
=> UI completed for Crossword and Nav bar

ProjectSourceCode/src/init_data/insert.sql
Created a 2nd CU Boulder-based crossword puzzle that can be selected by user.
=> Made a fully functional 2nd crossword puzzle

ProjectSourceCode/src/views/pages/trivia.hbs
Finished the Trivia Page UI and fixed some issues with Trivia.hbs
=> Finished Trivia Page UI

ProjectSourceCode/src/views/pages/geoGuess.hbs
I know we shouldn't commit to main but so be it. Some weird bug is occuring and this is the fix
=> Duplicate code during pull fix

ProjectSourceCode/src/init_data/create.sql, ProjectSourceCode/src/init_data/insert.sql
Wilson did this in the past but it got removed so here we are doing it again. All credit to wilson.
=> Added Trivia Questions

ProjectSourceCode/src/index.js, ProjectSourceCode/src/resources/css/crossword.css, ProjectSourceCode/src/resources/css/geoguessr.css, ProjectSourceCode/src/resources/css/wordle.css, ProjectSourceCode/src/resources/js/crossword.js, ProjectSourceCode/src/views/pages/home.hbs, ProjectSourceCode/src/views/pages/login.hbs, ProjectSourceCode/src/views/pages/logout.hbs, ProjectSourceCode/src/views/pages/register.hbs, ProjectSourceCode/src/views/pages/scoreboard.hbs, ProjectSourceCode/src/views/pages/trivia.hbs, ProjectSourceCode/src/views/partials/nav.hbs
Changed the crossword UI to be more consistent with the rest of the pages.
Added some UI to the logout page.
Got rid of the profile page.
Went through the CSS for every page and made sure the background-color was the same and the opacity for the background image set to 0.7.
=> changed crossword UI

ProjectSourceCode/src/views/pages/trivia.hbs
Updated the font of trivia to match the rest of the website.
=> changed trivia font

ProjectSourceCode/src/init_data/insert.sql
Added 11 questions of all three difficulty levels.
=> Added more Trivia Questions of all difficulties

ProjectSourceCode/src/resources/css/wordle.css
The Arial font in the background class was causing the navbar to also be Arial font. I put Arial font into the games-wrapper and took it out of background.
=> changed font

ProjectSourceCode/src/resources/js/wordle.js
Fixed an issue where saved guesses would get reset before the last guess was added.
=> Updated some function to be await and async
